GET http://localhost:3000/articles

###
GET http://localhost:3000/articles?title=나인

###
GET http://localhost:3000/articles/5002a911-3cae-423e-88c6-008f394b81c9
###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "사촌 비니",
  "content": "뉴욕 브루클린 출신의 7전8기 변호사 비니의 좌충우돌 첫 케이스! 비니는 사촌 빈센트의 살인누명을 벗겨줄 수 있을 것인가? 남주 조펫지 여주 마리사 토메이가 환상적인 연기의 궁합을 보이다!"
}

###
PATCH http://localhost:3000/articles/8f62cde2-e3c7-4e79-9167-baf41c9c5994
Content-Type: application/json

{
  "content": "남주 조 펫지와 여주 마리사 토메이의 궁합이 정말 잘 맞는 영화~"
}

###
DELETE http://localhost:3000/articles/8f62cde2-e3c7-4e79-9167-baf41c9c5994


###
POST http://localhost:3000/articles/42183d12-5a9c-49f1-bea3-861da70d5847/comments
Content-Type: application/json

{
  "content": "랄프 마치오도 굿"
}

###
GET http://localhost:3000/articles/42183d12-5a9c-49f1-bea3-861da70d5847/comments

###
DELETE http://localhost:3000/articles/42183d12-5a9c-49f1-bea3-861da70d5847/comments
