GET http://localhost:3001/comments


###
GET http://localhost:3001/comments/482decd2-2f7d-4e4f-accd-28893e286f92

###
POST http://localhost:3001/comments/articles/5002a911-3cae-423e-88c6-008f394b81c9
Content-Type: application/json

{
  "content": "이탈리아 피렌체가 배경인가 그래요. 아름답지요"
}

###
POST http://localhost:3001/comments/products/e48d9e8b-6712-48ed-9ea2-2f7e150a2e48
Content-Type: application/json

{
  "content": "다양한 풍미의 캡슐이 있어요!"
}

###
PATCH http://localhost:3001/comments/745277ae-e0eb-42fc-af10-d5961c8d46f4
Content-Type: application/json

{
  "content": "가성비 좋고 다양한 풍미의 캡슐커피!"
}

###
DELETE http://localhost:3001/comments/555786e1-441b-4d07-a317-4bfe00d10d3d

