GET http://localhost:3000/comments


###
GET http://localhost:3000/comments/cf8b9665-ca43-4358-b655-bd1f8f43eb9e

###
POST http://localhost:3000/comments/articles/9b8de731-b8d3-4bc2-a21f-5c9d6f83a9b9
Content-Type: application/json

{
  "content": "충격적인 결말"
}

###
POST http://localhost:3000/comments/products/b56e7a44-d39d-45c0-b5a2-fc7db9a5fca2
Content-Type: application/json

{
  "content": "몰입감 굿!"
}

###
PATCH http://localhost:3000/comments/29f3e207-72f3-4e24-a863-fca3d846e269
Content-Type: application/json

{
  "content": "집안을 영화관으로~"
}

###
DELETE http://localhost:3000/comments/7acf6b88-8b73-42a0-a8f1-a9b434d9eadc