//------------------------product image
GET http://localhost:3000/images/products/7f70481b-784d-4b0e-bc3e-f05eefc17951
//네스프레소    e48d9e8b-6712-48ed-9ea2-2f7e150a2e48
//아이폰17pro   f42bb363-e103-41db-9ced-af0cdbb5b532
//애플 airpod   7f70481b-784d-4b0e-bc3e-f05eefc17951
###
POST http://localhost:3000/images/products/7f70481b-784d-4b0e-bc3e-f05eefc17951
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="airPodPro.png"
Content-Type: image/png

< ./images/airPodPro.png
--MyBoundary--


###
DELETE http://localhost:3000/images/products/7f70481b-784d-4b0e-bc3e-f05eefc17951

