GET http://localhost:3000/products?order=recent
###
GET http://localhost:3000/products?offset=2

###
GET http://localhost:3000/products?name=프로
###
GET http://localhost:3000/products?description=보습

###
GET http://localhost:3000/products/d48cb489-11f5-4796-8b5c-dc0204e7e09e

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "iPhone 17 Pro",
  "description": "최신 아이폰",
  "price": 1790000,
  "tags": ["전자제품", "스마트폰"]
}

###
PATCH http://localhost:3000/products/d48cb489-11f5-4796-8b5c-dc0204e7e09e
Content-Type: application/json

{
  "description": "2025년 10월 한국에 발매 시작한 최신 아이폰으로 8배 광학줌을 가진 후면 카메라가 압권입니다.",
  "price": 1790000,
  "tags": ["전자제품", "스마트폰", "경량 케이스"]
}

###
DELETE http://localhost:3000/products/d48cb489-11f5-4796-8b5c-dc0204e7e09e

//---------------------comments 관련
###
POST http://localhost:3000/products/6c292255-7344-4715-a3e8-7f801f5a1ae5/comments
Content-Type: application/json

{
  "content": "아이폰은 진리."
}

###
GET http://localhost:3000/products/6c292255-7344-4715-a3e8-7f801f5a1ae5/comments

###
DELETE http://localhost:3000/products/d48cb489-11f5-4796-8b5c-dc0204e7e09e/comments

###
DELETE http://localhost:3000/products/6c292255-7344-4715-a3e8-7f801f5a1ae5/comments/69c065c5-6a68-44c4-bdba-4c21ebd5a876